spring:
  application:
    name: tasktrace-discovery-service

server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,logfile"
  health:
    defaults:
      enabled: true

logging:
  file:
    name: ./logs/tasktrace-discovery-service.log

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 5
    registry-sync-retries: 3
    max-threads-for-peer-replication: 0

